// Written by tools/generate_voice.py. Maps a step or view id to its recording.
const NARRATION = {
  "view-use": "audio/view-use.mp3",
  "prompt": "audio/prompt.mp3",
  "tokens": "audio/tokens.mp3",
  "ids": "audio/ids.mp3",
  "embeddings": "audio/embeddings.mp3",
  "network": "audio/network.mp3",
  "attention": "audio/attention.mp3",
  "prediction": "audio/prediction.mp3",
  "sampling": "audio/sampling.mp3",
  "loop": "audio/loop.mp3",
  "view-train": "audio/view-train.mp3",
  "data": "audio/data.mp3",
  "pretraining": "audio/pretraining.mp3",
  "descent": "audio/descent.mp3",
  "posttraining": "audio/posttraining.mp3",
  "feedback": "audio/feedback.mp3",
  "evaluation": "audio/evaluation.mp3",
  "adapting": "audio/adapting.mp3",
  "view-agents": "audio/view-agents.mp3",
  "agentic": "audio/agentic.mp3",
  "harness": "audio/harness.mp3",
  "chain": "audio/chain.mp3",
  "mcp": "audio/mcp.mp3",
  "trust": "audio/trust.mp3",
  "view-mind": "audio/view-mind.mp3",
  "memory": "audio/memory.mp3",
  "brain": "audio/brain.mp3",
  "questions": "audio/questions.mp3"
};
